---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
after_success:
  ["git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng", ".forge-releng/publish"]
env:
  global:
    - PUBLISHER_LOGIN=camptocamp
    - secure: "bB20F09Yuj4OdELOAczuhd8MobDGbZ9FOH4LF1N34htgfJ/HrT57chodY40543Hgn2dbcXGlVZTh5q637soYyE2jnkfEGT+nVZMUqY+Pu5ecrygTJpCnIVqWcCG2Bx+/O0+FLfIjt/aDD34jVACWcx7LlqwXUpvU1lQQAgZawf4="
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
